### PR TITLE
#70: Error handling (closes #70)

### LINKED ISSUE #70: Error handling
[Trello card](https://trello.com/c/58230ff07fa5b144c167c77f/)

* document errors in Readme
* create taxonomy of Exceptions
  - Have a root parent exception.
  - Differentiate between unrecoverable exceptions and transient exceptions.
  - Hide implementation details like Http
* methods returning `boolean` should return `void`, and throw an appropriate exception in case of errors

### PR DESCRIPTION
**Pull request by dhinus**
Closes #70

### tests performed
* ✅ sbt test
* ✅ sbt example/run

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/main/java/it/contactlab/hub/sdk/java/exceptions/ApiException.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+      if (!jsonResponse.isJsonObject()) {
+        throw new ServerException(statusCode, responseBody);
+      }
+
+      this.errorMessage = jsonResponse.getAsJsonObject()
+                                      .get("message").getAsString();
+    } catch (JsonSyntaxException jsonException) {
+      throw new ServerException(statusCode, responseBody);
+    }
+  }
```
Comment (bytecodeguru) [inline src/main/java/it/contactlab/hub/sdk/java/exceptions/ApiException.java]: A custom exception constructor that throws... sounds confusing. Let's refactor this into a factory method `String ApiExcepition.extractMessage(String responseBody)`

File: src/main/java/it/contactlab/hub/sdk/java/exceptions/ApiException.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
+package it.contactlab.hub.sdk.java.exceptions;
+
+import com.google.gson.JsonElement;
+import com.google.gson.JsonObject;
+import com.google.gson.JsonParser;
+import com.google.gson.JsonSyntaxException;
+
+public class ApiException extends ServerException {
```
Comment (bytecodeguru) [inline src/main/java/it/contactlab/hub/sdk/java/exceptions/ApiException.java]: Let's extend ContactHubException instead, as ApiException is semantically different from ServerException. A bit of code duplication (common subset of private fields) in this case won't hurt.

File: src/main/java/it/contactlab/hub/sdk/java/internal/api/CustomerApi.java [hunk 3]
```diff
@@ -72,16 +76,13 @@ public static Customer get(Auth auth, String id) throws HttpException {
...
-    Type collectionType = new TypeToken<List<Customer>>(){}.getType();
+    String response = Request.doGet(auth, endpoint, queryString);
 
-    List<Customer> customers = gson.fromJson(response
-        .getJSONArray("elements")
-        .toString(),
-        collectionType);
+    JsonParser parser = new JsonParser();
+    JsonObject jsonResponse = parser.parse(response).getAsJsonObject();
+    Customer[] customers = gson.fromJson(jsonResponse.get("elements"), Customer[].class);
```
Comment (bytecodeguru) [inline src/main/java/it/contactlab/hub/sdk/java/internal/api/CustomerApi.java]: 💯
